// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPTApi.Model;

#nullable disable

namespace PPTApi.Migrations
{
    [DbContext(typeof(PptDbContext))]
    partial class PptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PPTApi.Model.PPTDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DriveFileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveFilepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PptFileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PptFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PptDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
